### PR TITLE
Make SSR hydration work for Desktop

### PR DESCRIPTION
**Pull request by xeoneux**
Currently, SSR is not working for Desktop media because React hydration is failing as the useMatchMedia check is different on the server and on the client (it's working for Mobile media though). This uses Fresnel to fix that make SSR work for Preshape when accessed using a Desktop.

Current:
Screenshot 2023-11-16 at 12 31 50 pm

"Hydration failed because the initial UI does not match what was rendered on the server."

@HHogg

### CODE REVIEW

**Comment by HHogg** [comment]
Thanks for the PR @xeoneux, just letting you know I've now seen it and will take a look a bit later today.

**Comment by HHogg** [comment]
Hi @xeoneux I've taken a look at this and played around with some different options. I think the approach Fresnel has taken is something along the lines of making this work. 

One issue with the approach is around the margin pattern I've baked into the Box component, where margins are applied and removed based on other sibling elements, so rendering both elements can interfere with that. 

Another issue is that the `useMatchMedia` isn't just used for conditional rendering whole elements, but is used for conditional prop values too which again wont really solve the hydration issue. 

This is something I've known has been an issue for a while but never really prioritised it, however I do need to sort this for another reason so it's something I'm going to actively work on now in my spare time.

**Comment by HHogg** [comment]
> If utilizing SSR rendering features, when the markup is passed down from the server to the client it includes all breakpoints, which increases the page size. (However, once the client mounts, the unused breakpoint markup is cleared from the DOM.)

This probably gets around the margin issue then, so just need to solve the conditional prop challenges.

**Comment by HHogg** [comment]
Hey @xeoneux would you mind fixing the conflict, and we can merge this in?

**Comment by HHogg** [comment]
I've pushed up some changes to the package that will help fix some layout bits with fresnel and other bits to help with the SSG (removing the responsiveness inside Modal).

**Comment by xeoneux** [comment]
Hi @HHogg, I have updated the PR with the latest code 😄

**Comment by HHogg** [comment]
Thanks a lot @xeoneux

**Pull request merged**
